package com.pmgt.pos.closing

import com.pmgt.pos.printer.*
import java.math.BigDecimal
import java.math.RoundingMode
import java.time.format.DateTimeFormatter
import java.util.Locale

/** Pure, call-for-call port of the invoked React Native Z-report formatter. */
object ZReportFormatter {
    fun format(document: ZReportDocument, charsPerLine: Int): List<PrinterCall> = buildList {
        val data = document.report
        val width = charsPerLine
        val feed = if (width >= 48) "\n\n\n\n\n\n" else "\n\n\n"

        align(PrinterAlignment.CENTER)
        text("${document.storeName}\n", BOLD)
        document.storeAddress.ifTruthy { text("$it\n") }
        document.storeTin.ifTruthy { text("TIN: $it\n") }
        text("\n")
        text("Z-REPORT / END OF DAY\n", LARGE)
        text("\n")
        text("${data.reportDate}\n", BOLD)
        if (data.startTime != null && data.endTime != null) {
            val suffix = if (data.endTime <= data.startTime) " (next day)" else ""
            text("${displayTime(data.startTime)} - ${displayTime(data.endTime)}$suffix\n")
        }
        align(PrinterAlignment.LEFT)
        text("${line('=', width)}\n")
        text("${row("Gross Sales", currency(data.grossSales), width)}\n", BOLD)
        text("${row("Less Discounts", "-${currency(data.totalDiscounts)}", width)}\n")
        text("${line('-', width)}\n")
        text("${row("NET SALES", currency(data.netSales), width)}\n", BOLD)
        text("\n")
        text("${row("Transactions", data.transactionCount.toString(), width)}\n")
        text("${row("Average Ticket", currency(data.averageTicket), width)}\n")
        text("\n")

        section("PAYMENT BREAKDOWN", width)
        text("${row("Cash", currency(data.cashTotal), width)}\n")
        text("${row("Card/E-Wallet", currency(data.cardEwalletTotal), width)}\n")
        text("${line('-', width)}\n")
        text("${row("TOTAL COLLECTED", currency(data.cashTotal + data.cardEwalletTotal), width)}\n", BOLD)
        text("\n")

        section("DISCOUNT BREAKDOWN", width)
        text("${row("Senior", currency(data.seniorDiscounts), width)}\n")
        text("${row("PWD", currency(data.pwdDiscounts), width)}\n")
        text("${row("Promo", currency(data.promoDiscounts), width)}\n")
        text("${row("Manual", currency(data.manualDiscounts), width)}\n")
        text("${line('-', width)}\n")
        text("${row("Total Discounts", currency(data.totalDiscounts), width)}\n", BOLD)
        text("\n")

        section("VOIDS", width)
        text("${row("Void Count", data.voidCount.toString(), width)}\n")
        text("${row("Void Amount", currency(data.voidAmount), width)}\n")
        text("\n")

        section("VAT SUMMARY", width)
        text("${row("VATable Sales", currency(data.vatableSales), width)}\n")
        text("${row("VAT Amount 12%", currency(data.vatAmount), width)}\n")
        text("${row("VAT-Exempt", currency(data.vatExemptSales), width)}\n")
        text("${row("Non-VAT", currency(data.nonVatSales), width)}\n")
        text("${line('=', width)}\n")

        if (document.productSales.isNotEmpty()) items(document.productSales, width)
        if (document.paymentTransactions.isNotEmpty()) payments(document.paymentTransactions, width)

        align(PrinterAlignment.CENTER)
        text("Generated by: ${data.generatedByName}\n")
        text("Printed: ${document.printedAt.format(PRINTED)}\n")
        text("** system-generated **\n")
        text("Powered by PMGT Flow Suite$feed", cut = true)
    }
}

private val NORMAL = PrinterTextStyle()
private val BOLD = PrinterTextStyle(heightTimes = 1)
private val LARGE = PrinterTextStyle(widthTimes = 1, heightTimes = 1)
private val PRINTED = DateTimeFormatter.ofPattern("MM/dd/yyyy, hh:mm:ss a", Locale.US)

private fun MutableList<PrinterCall>.align(value: PrinterAlignment) {
    add(PrinterCall.Align(value))
}

private fun MutableList<PrinterCall>.text(
    value: String,
    style: PrinterTextStyle = NORMAL,
    cut: Boolean = false,
) {
    add(PrinterCall.Text(value, style, cut))
}

private fun MutableList<PrinterCall>.section(title: String, width: Int) {
    align(PrinterAlignment.CENTER)
    text("$title\n", BOLD)
    align(PrinterAlignment.LEFT)
    text("${line('-', width)}\n")
}

private fun MutableList<PrinterCall>.items(items: List<ProductSale>, width: Int) {
    text("\n")
    align(PrinterAlignment.CENTER)
    text("ITEMS SOLD\n", BOLD)
    align(PrinterAlignment.LEFT)
    text("${line('-', width)}\n")
    val quantityWidth = 5
    val amountWidth = 10
    val nameWidth = width - quantityWidth - amountWidth - 2
    text("${"Item".padEnd(nameWidth)} ${"Qty".padStart(quantityWidth)} ${"Amt".padStart(amountWidth)}\n")
    val groups = items.groupBy { it.categoryName.ifEmpty { "Uncategorized" } }.toSortedMap()
    var totalQuantity = 0.0
    var totalAmount = 0.0
    groups.forEach { (category, categoryItems) ->
        val label = "-- $category "
        text("$label${line('-', (width - label.length).coerceAtLeast(0))}\n", BOLD)
        var categoryQuantity = 0.0
        var categoryAmount = 0.0
        categoryItems.sortedByDescending { it.quantitySold }.forEach { item ->
            categoryQuantity += item.quantitySold
            categoryAmount += item.grossAmount
            val name =
                if (item.productName.length > nameWidth) item.productName.substring(0, nameWidth)
                else item.productName.padEnd(nameWidth)
            text(
                "$name ${jsNumber(item.quantitySold).padStart(quantityWidth)} " +
                    "${currency(item.grossAmount).padStart(amountWidth)}\n"
            )
        }
        text("${line('-', width)}\n")
        text(
            "${"Subtotal".padEnd(nameWidth)} ${jsNumber(categoryQuantity).padStart(quantityWidth)} " +
                "${currency(categoryAmount).padStart(amountWidth)}\n",
            BOLD,
        )
        text("\n")
        totalQuantity += categoryQuantity
        totalAmount += categoryAmount
    }
    text("${line('-', width)}\n")
    text(
        "${"Total".padEnd(nameWidth)} ${jsNumber(totalQuantity).padStart(quantityWidth)} " +
            "${currency(totalAmount).padStart(amountWidth)}\n",
        BOLD,
    )
    text("${line('=', width)}\n")
}

private fun MutableList<PrinterCall>.payments(groups: List<PaymentTransactionGroup>, width: Int) {
    text("\n")
    align(PrinterAlignment.CENTER)
    text("PAYMENT TRANSACTIONS\n", BOLD)
    align(PrinterAlignment.LEFT)
    groups.forEach { group ->
        val label = "-- ${group.paymentType} "
        text("$label${line('-', (width - label.length).coerceAtLeast(0))}\n", BOLD)
        group.transactions.forEach { transaction ->
            text(
                "${row("#${transaction.orderNumber}  ${transaction.referenceNumber}", currency(transaction.amount), width)}\n"
            )
        }
        text("${line('-', width)}\n")
        text("${row("Subtotal", currency(group.subtotal), width)}\n", BOLD)
        text("\n")
    }
    text("${line('=', width)}\n")
}

private fun line(character: Char, width: Int) = character.toString().repeat(width.coerceAtLeast(0))

private fun row(left: String, right: String, width: Int): String {
    val gap = width - left.length - right.length
    if (gap >= 1) return left + " ".repeat(gap) + right
    val end = width - right.length - 1
    val normalized =
        if (end < 0) (left.length + end).coerceAtLeast(0) else end.coerceAtMost(left.length)
    return left.substring(0, normalized) + " " + right
}

private fun currency(value: Double): String {
    val fixed = jsToFixed2(value)
    val sign = if (fixed.startsWith('-')) "-" else ""
    val unsigned = fixed.removePrefix("-")
    val decimal = unsigned.indexOf('.')
    val integer = if (decimal >= 0) unsigned.substring(0, decimal) else unsigned
    val fraction = if (decimal >= 0) unsigned.substring(decimal) else ""
    return "P $sign${integer.reversed().chunked(3).joinToString(",").reversed()}$fraction"
}

private fun jsToFixed2(value: Double): String =
    when {
        value.isNaN() -> "NaN"
        value == Double.POSITIVE_INFINITY -> "Infinity"
        value == Double.NEGATIVE_INFINITY -> "-Infinity"
        kotlin.math.abs(value) >= 1e21 -> jsNumber(value)
        else -> BigDecimal(value).setScale(2, RoundingMode.HALF_UP).toPlainString()
    }

private fun jsNumber(value: Double): String {
    if (value == 0.0) return "0"
    if (value.isNaN()) return "NaN"
    if (value == Double.POSITIVE_INFINITY) return "Infinity"
    if (value == Double.NEGATIVE_INFINITY) return "-Infinity"
    val absolute = kotlin.math.abs(value)
    val decimal = BigDecimal.valueOf(value).stripTrailingZeros()
    if (absolute >= 1e-6 && absolute < 1e21) return decimal.toPlainString()
    val exponent = decimal.precision() - decimal.scale() - 1
    val coefficient = decimal.movePointLeft(exponent).stripTrailingZeros().toPlainString()
    return "$coefficient" + "e" + if (exponent >= 0) "+$exponent" else exponent.toString()
}

private fun displayTime(value: String): String {
    val (hour, minute) = value.split(':').map(String::toInt)
    return "${(hour % 12).takeUnless { it == 0 } ?: 12}:" +
        "${minute.toString().padStart(2, '0')} ${if (hour >= 12) "PM" else "AM"}"
}

private inline fun String?.ifTruthy(block: (String) -> Unit) {
    if (!isNullOrEmpty()) block(this)
}
