// Generate, or verify, the Kotlin compatibility schema from the shipped RN source.
// The fixture and DDL use WatermelonDB's real encoder, including untyped columns.
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const ts = require("typescript");
const root = path.resolve(__dirname, "../../..");
const source = fs.readFileSync(path.join(root, "apps/native/src/db/schema.ts"), "utf8");
const moduleValue = { exports: {} };
vm.runInNewContext(ts.transpileModule(source, {
  compilerOptions: { module: ts.ModuleKind.CommonJS },
}).outputText, { exports: moduleValue.exports, require });
const schema = moduleValue.exports.watermelonSchema;
const { encodeSchema } = require("@nozbe/watermelondb/adapters/sqlite/encodeSchema");
const sql = encodeSchema(schema).replaceAll(";", ";\n").replace(/\b(create table|create index|if not exists|primary key|not null|varchar|text|on)\b/g, s => s.toUpperCase());
const tables = Object.values(schema.tables);
// SQLDelight's parser requires declared types and does not accept VARCHAR(16).
// These are query/model declarations only. LegacySqlSchema creates the exact untyped DDL.
const declarations = `CREATE TABLE local_storage (key TEXT NOT NULL PRIMARY KEY, value TEXT NOT NULL);\n` + tables.map(t => {
  const fields = ['id TEXT PRIMARY KEY', '_changed TEXT', '_status TEXT', ...Object.values(t.columns).map(c => `"${c.name}" ${c.type === "string" ? "TEXT" : c.type === "boolean" ? "INTEGER" : "REAL"}`)];
  return `CREATE TABLE "${t.name}" (${fields.join(", ")});\n`;
}).join("");
const kotlin = `// Generated by scripts/legacy-schema.cjs; do not edit.\npackage com.pmgt.pos.db\n\ninternal object LegacyTables {\n    const val version = ${schema.version}\n    val tables: Map<String, List<LegacyColumn>> = linkedMapOf(\n${tables.map(t => `        "${t.name}" to listOf(\n${Object.values(t.columns).map(c => `            LegacyColumn("${c.name}", "${c.type}", ${!!c.isOptional}),`).join("\n")}\n        ),`).join("\n")}\n    )\n    val localOnly = setOf("sync_meta", "sync_v2_aggregates")\n}\n`;
const files = {
  "app/src/main/sqldelight/com/pmgt/pos/db/generated/Legacy.sq": `-- Generated logical declarations ONLY; LegacySqlSchema owns physical DDL.\n${declarations}\nreadLocalValue:\nSELECT value FROM local_storage WHERE key = ?;\n`,
  "app/src/main/java/com/pmgt/pos/db/LegacyTables.kt": kotlin,
  "app/src/main/java/com/pmgt/pos/db/LegacyDdl.kt": `// Generated exact WatermelonDB DDL. Never substitute generated logical Schema.create.\npackage com.pmgt.pos.db\n\ninternal object LegacyDdl {\n    val statements = \"\"\"\n${sql}\"\"\".split(';').filter { it.isNotBlank() }\n}\n`,
  "app/src/test/resources/legacy-v3.sql": `${sql}PRAGMA user_version = ${schema.version};\n`,
};
for (const [relative, content] of Object.entries(files)) {
  const target = path.join(__dirname, "..", relative);
  if (process.argv.includes("--write")) {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content);
  } else if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== content) {
    throw new Error(`Generated schema out of date: ${relative}; run node apps/android/scripts/legacy-schema.cjs --write`);
  }
}
console.log(`Verified legacy schema v${schema.version}: ${tables.length} model tables plus local_storage.`);
