// Generated exact WatermelonDB DDL. Never substitute generated logical Schema.create.
package com.pmgt.pos.db

internal object LegacyDdl {
    val statements = """
CREATE TABLE "local_storage" ("key" VARCHAR(16) PRIMARY KEY NOT NULL, "value" TEXT NOT NULL);
CREATE INDEX "local_storage_key_index" ON "local_storage" ("key");
CREATE TABLE "categories" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "store_id", "name", "parent_id", "sort_order", "is_active", "created_at", "updated_at");
CREATE INDEX IF NOT EXISTS "categories_server_id" ON "categories" ("server_id");
CREATE INDEX IF NOT EXISTS "categories_store_id" ON "categories" ("store_id");
CREATE INDEX IF NOT EXISTS "categories_parent_id" ON "categories" ("parent_id");
CREATE INDEX IF NOT EXISTS "categories__status" ON "categories" ("_status");
CREATE TABLE "products" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "store_id", "name", "category_id", "price", "is_vatable", "is_active", "is_open_price", "min_price", "max_price", "sort_order", "created_at", "updated_at");
CREATE INDEX IF NOT EXISTS "products_server_id" ON "products" ("server_id");
CREATE INDEX IF NOT EXISTS "products_store_id" ON "products" ("store_id");
CREATE INDEX IF NOT EXISTS "products_category_id" ON "products" ("category_id");
CREATE INDEX IF NOT EXISTS "products_is_active" ON "products" ("is_active");
CREATE INDEX IF NOT EXISTS "products__status" ON "products" ("_status");
CREATE TABLE "modifier_groups" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "store_id", "name", "selection_type", "min_selections", "max_selections", "sort_order", "is_active", "created_at", "updated_at");
CREATE INDEX IF NOT EXISTS "modifier_groups_server_id" ON "modifier_groups" ("server_id");
CREATE INDEX IF NOT EXISTS "modifier_groups_store_id" ON "modifier_groups" ("store_id");
CREATE INDEX IF NOT EXISTS "modifier_groups__status" ON "modifier_groups" ("_status");
CREATE TABLE "modifier_options" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "store_id", "modifier_group_id", "name", "price_adjustment", "is_default", "is_available", "sort_order", "created_at", "updated_at");
CREATE INDEX IF NOT EXISTS "modifier_options_server_id" ON "modifier_options" ("server_id");
CREATE INDEX IF NOT EXISTS "modifier_options_store_id" ON "modifier_options" ("store_id");
CREATE INDEX IF NOT EXISTS "modifier_options_modifier_group_id" ON "modifier_options" ("modifier_group_id");
CREATE INDEX IF NOT EXISTS "modifier_options__status" ON "modifier_options" ("_status");
CREATE TABLE "modifier_group_assignments" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "store_id", "modifier_group_id", "product_id", "category_id", "sort_order", "min_selections_override", "max_selections_override", "created_at", "updated_at");
CREATE INDEX IF NOT EXISTS "modifier_group_assignments_server_id" ON "modifier_group_assignments" ("server_id");
CREATE INDEX IF NOT EXISTS "modifier_group_assignments_store_id" ON "modifier_group_assignments" ("store_id");
CREATE INDEX IF NOT EXISTS "modifier_group_assignments_modifier_group_id" ON "modifier_group_assignments" ("modifier_group_id");
CREATE INDEX IF NOT EXISTS "modifier_group_assignments_product_id" ON "modifier_group_assignments" ("product_id");
CREATE INDEX IF NOT EXISTS "modifier_group_assignments_category_id" ON "modifier_group_assignments" ("category_id");
CREATE INDEX IF NOT EXISTS "modifier_group_assignments__status" ON "modifier_group_assignments" ("_status");
CREATE TABLE "tables" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "store_id", "name", "capacity", "status", "current_order_id", "sort_order", "is_active", "created_at", "updated_at");
CREATE INDEX IF NOT EXISTS "tables_server_id" ON "tables" ("server_id");
CREATE INDEX IF NOT EXISTS "tables_store_id" ON "tables" ("store_id");
CREATE INDEX IF NOT EXISTS "tables_status" ON "tables" ("status");
CREATE INDEX IF NOT EXISTS "tables__status" ON "tables" ("_status");
CREATE TABLE "orders" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "store_id", "order_number", "order_type", "order_channel", "takeout_status", "table_id", "customer_name", "draft_label", "status", "gross_sales", "vatable_sales", "vat_amount", "vat_exempt_sales", "non_vat_sales", "discount_amount", "net_sales", "payment_method", "cash_received", "change_given", "card_payment_type", "card_reference_number", "order_category", "table_marker", "created_by", "created_at", "paid_at", "paid_by", "pax", "tab_number", "tab_name", "request_id", "table_name", "item_count", "origin_device_id", "refunded_from_order_id", "updated_at");
CREATE INDEX IF NOT EXISTS "orders_server_id" ON "orders" ("server_id");
CREATE INDEX IF NOT EXISTS "orders_store_id" ON "orders" ("store_id");
CREATE INDEX IF NOT EXISTS "orders_table_id" ON "orders" ("table_id");
CREATE INDEX IF NOT EXISTS "orders_status" ON "orders" ("status");
CREATE INDEX IF NOT EXISTS "orders_refunded_from_order_id" ON "orders" ("refunded_from_order_id");
CREATE INDEX IF NOT EXISTS "orders__status" ON "orders" ("_status");
CREATE TABLE "order_items" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "order_id", "product_id", "product_name", "product_price", "quantity", "notes", "service_type", "is_voided", "is_sent_to_kitchen", "voided_by", "voided_at", "void_reason", "updated_at");
CREATE INDEX IF NOT EXISTS "order_items_server_id" ON "order_items" ("server_id");
CREATE INDEX IF NOT EXISTS "order_items_order_id" ON "order_items" ("order_id");
CREATE INDEX IF NOT EXISTS "order_items_product_id" ON "order_items" ("product_id");
CREATE INDEX IF NOT EXISTS "order_items__status" ON "order_items" ("_status");
CREATE TABLE "order_item_modifiers" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "order_item_id", "modifier_group_name", "modifier_option_name", "price_adjustment", "updated_at");
CREATE INDEX IF NOT EXISTS "order_item_modifiers_server_id" ON "order_item_modifiers" ("server_id");
CREATE INDEX IF NOT EXISTS "order_item_modifiers_order_item_id" ON "order_item_modifiers" ("order_item_id");
CREATE INDEX IF NOT EXISTS "order_item_modifiers__status" ON "order_item_modifiers" ("_status");
CREATE TABLE "order_discounts" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "order_id", "order_item_id", "discount_type", "customer_name", "customer_id", "quantity_applied", "discount_amount", "vat_exempt_amount", "approved_by", "created_at", "updated_at");
CREATE INDEX IF NOT EXISTS "order_discounts_server_id" ON "order_discounts" ("server_id");
CREATE INDEX IF NOT EXISTS "order_discounts_order_id" ON "order_discounts" ("order_id");
CREATE INDEX IF NOT EXISTS "order_discounts__status" ON "order_discounts" ("_status");
CREATE TABLE "order_voids" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "order_id", "void_type", "order_item_id", "reason", "approved_by", "requested_by", "amount", "created_at", "refund_method", "replacement_order_id", "updated_at");
CREATE INDEX IF NOT EXISTS "order_voids_server_id" ON "order_voids" ("server_id");
CREATE INDEX IF NOT EXISTS "order_voids_order_id" ON "order_voids" ("order_id");
CREATE INDEX IF NOT EXISTS "order_voids__status" ON "order_voids" ("_status");
CREATE TABLE "order_payments" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "order_id", "store_id", "payment_method", "amount", "cash_received", "change_given", "card_payment_type", "card_reference_number", "created_at", "created_by", "updated_at");
CREATE INDEX IF NOT EXISTS "order_payments_server_id" ON "order_payments" ("server_id");
CREATE INDEX IF NOT EXISTS "order_payments_order_id" ON "order_payments" ("order_id");
CREATE INDEX IF NOT EXISTS "order_payments_store_id" ON "order_payments" ("store_id");
CREATE INDEX IF NOT EXISTS "order_payments__status" ON "order_payments" ("_status");
CREATE TABLE "users" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "name", "email", "role_id", "store_id", "pin", "is_active", "updated_at");
CREATE INDEX IF NOT EXISTS "users_server_id" ON "users" ("server_id");
CREATE INDEX IF NOT EXISTS "users_store_id" ON "users" ("store_id");
CREATE INDEX IF NOT EXISTS "users__status" ON "users" ("_status");
CREATE TABLE "roles" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "name", "permissions", "scope_level", "is_system", "updated_at");
CREATE INDEX IF NOT EXISTS "roles_server_id" ON "roles" ("server_id");
CREATE INDEX IF NOT EXISTS "roles__status" ON "roles" ("_status");
CREATE TABLE "stores" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "name", "parent_id", "logo", "address1", "address2", "tin", "min", "vat_rate", "printer_mac", "kitchen_printer_mac", "contact_number", "telephone", "email", "website", "footer", "schedule_json", "is_active", "created_at", "device_code_counter", "updated_at");
CREATE INDEX IF NOT EXISTS "stores_server_id" ON "stores" ("server_id");
CREATE INDEX IF NOT EXISTS "stores__status" ON "stores" ("_status");
CREATE TABLE "settings" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "store_id", "key", "value", "updated_at");
CREATE INDEX IF NOT EXISTS "settings_server_id" ON "settings" ("server_id");
CREATE INDEX IF NOT EXISTS "settings_store_id" ON "settings" ("store_id");
CREATE INDEX IF NOT EXISTS "settings_key" ON "settings" ("key");
CREATE INDEX IF NOT EXISTS "settings__status" ON "settings" ("_status");
CREATE TABLE "app_config" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "key", "value", "store_id", "updated_at");
CREATE INDEX IF NOT EXISTS "app_config_server_id" ON "app_config" ("server_id");
CREATE INDEX IF NOT EXISTS "app_config_key" ON "app_config" ("key");
CREATE INDEX IF NOT EXISTS "app_config__status" ON "app_config" ("_status");
CREATE TABLE "audit_logs" ("id" PRIMARY KEY, "_changed", "_status", "server_id", "store_id", "action", "entity_type", "entity_id", "details", "user_id", "created_at", "updated_at");
CREATE INDEX IF NOT EXISTS "audit_logs_server_id" ON "audit_logs" ("server_id");
CREATE INDEX IF NOT EXISTS "audit_logs_store_id" ON "audit_logs" ("store_id");
CREATE INDEX IF NOT EXISTS "audit_logs_action" ON "audit_logs" ("action");
CREATE INDEX IF NOT EXISTS "audit_logs_entity_id" ON "audit_logs" ("entity_id");
CREATE INDEX IF NOT EXISTS "audit_logs__status" ON "audit_logs" ("_status");
CREATE TABLE "sync_meta" ("id" PRIMARY KEY, "_changed", "_status", "key", "value");
CREATE INDEX IF NOT EXISTS "sync_meta_key" ON "sync_meta" ("key");
CREATE INDEX IF NOT EXISTS "sync_meta__status" ON "sync_meta" ("_status");
CREATE TABLE "sync_v2_aggregates" ("id" PRIMARY KEY, "_changed", "_status", "store_id", "order_id", "aggregate_version", "payload", "updated_at");
CREATE INDEX IF NOT EXISTS "sync_v2_aggregates_store_id" ON "sync_v2_aggregates" ("store_id");
CREATE INDEX IF NOT EXISTS "sync_v2_aggregates_order_id" ON "sync_v2_aggregates" ("order_id");
CREATE INDEX IF NOT EXISTS "sync_v2_aggregates__status" ON "sync_v2_aggregates" ("_status");
""".split(';').filter { it.isNotBlank() }
}
